# Sequences: the pre-12c Oracle primary-key pattern, and IDENTITY columns from
# 12c onward. `seq.NEXTVAL` / `seq.CURRVAL` are Oracle-specific syntax that must
# be rewritten to nextval('seq') / currval('seq').

-- case: create_sequence
CREATE SEQUENCE ord_seq START WITH 1 INCREMENT BY 1
-- rowcount: 0
-- end

-- case: nextval_from_dual
-- setup: CREATE SEQUENCE s1 START WITH 10
SELECT s1.NEXTVAL FROM DUAL
-- expect:
10
-- end

-- case: nextval_then_currval
-- setup: CREATE SEQUENCE s2 START WITH 5
-- setup: SELECT s2.NEXTVAL FROM DUAL
SELECT s2.CURRVAL FROM DUAL
-- expect:
5
-- end

-- case: nextval_increments
-- setup: CREATE SEQUENCE s3 START WITH 1 INCREMENT BY 1
-- setup: SELECT s3.NEXTVAL FROM DUAL
SELECT s3.NEXTVAL FROM DUAL
-- expect:
2
-- end

-- case: nextval_in_insert
-- setup: CREATE SEQUENCE s4 START WITH 100
-- setup: CREATE TABLE seq_ins (id INT PRIMARY KEY, note TEXT)
-- setup: INSERT INTO seq_ins (id, note) VALUES (s4.NEXTVAL, 'first')
SELECT id, note FROM seq_ins
-- expect:
100 | first
-- end

-- case: nextval_increment_by_ten
-- setup: CREATE SEQUENCE s5 START WITH 0 INCREMENT BY 10 MINVALUE 0
-- setup: SELECT s5.NEXTVAL FROM DUAL
SELECT s5.NEXTVAL FROM DUAL
-- expect:
10
-- end

-- case: identity_column_autofills
-- setup: CREATE TABLE id_tbl (id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, label VARCHAR2(20))
-- setup: INSERT INTO id_tbl (label) VALUES ('a')
-- setup: INSERT INTO id_tbl (label) VALUES ('b')
SELECT id, label FROM id_tbl ORDER BY id
-- expect:
1 | a
2 | b
-- end

-- case: identity_by_default
-- setup: CREATE TABLE id_def (id NUMBER GENERATED BY DEFAULT AS IDENTITY, label VARCHAR2(20))
-- setup: INSERT INTO id_def (label) VALUES ('x')
SELECT id FROM id_def
-- expect:
1
-- end

-- case: drop_sequence
-- setup: CREATE SEQUENCE s6
DROP SEQUENCE s6
-- rowcount: 0
-- end

-- case: currval_before_nextval_errors
-- setup: CREATE SEQUENCE s7
SELECT s7.CURRVAL FROM DUAL
-- error: currval
-- end
